[package]
name = "rust_balanced_brackets"
version = "0.1.0"
authors = ["Anthony Scotti <anthony.m.scotti@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "3.2.14", features = ["derive"] }
rayon = "1.5"